import { Account } from "@/types/account";

export const mockAccounts: Account[] = [
  {
    id: 1,
    handle: "alice.lens",
    name: "Alice",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Digital artist and NFT creator",
    posts: 127,
    followers: 3420,
  },
  {
    id: 2,
    handle: "bob.lens",
    name: "Bob",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Crypto enthusiast | Web3 developer",
    posts: 89,
    followers: 1250,
  },
  {
    id: 3,
    handle: "charlie.lens",
    name: "Charlie",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Sharing thoughts on DeFi and the future of finance",
    posts: 215,
    followers: 5600,
  },
  {
    id: 4,
    handle: "diana.lens",
    name: "Diana",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Artist • Writer • Creator",
    posts: 76,
    followers: 980,
  },
  {
    id: 5,
    handle: "evan.lens",
    name: "Evan",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Building the decentralized future | Solidity dev",
    posts: 132,
    followers: 2340,
  },
  {
    id: 6,
    handle: "fiona.lens",
    name: "Fiona",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Photography and blockchain technology",
    posts: 54,
    followers: 760,
  },
  {
    id: 7,
    handle: "greg.lens",
    name: "Greg",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Memes and dreams",
    posts: 310,
    followers: 8900,
  },
  {
    id: 8,
    handle: "hannah.lens",
    name: "Hannah",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Exploring web3 social graphs",
    posts: 92,
    followers: 1870,
  },
  {
    id: 9,
    handle: "ian.lens",
    name: "Ian",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Musician and NFT collector",
    posts: 63,
    followers: 1120,
  },
  {
    id: 10,
    handle: "julia.lens",
    name: "Julia",
    avatar: "/placeholder.svg?height=100&width=100",
    bio: "Documenting my web3 journey",
    posts: 147,
    followers: 2560,
  },
];
